name: Run MATLAB Scripts
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  my-job:
    name: Run MATLAB Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024a
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: irest-matlab/toy_example.m
