name: Run MATLAB Scripts
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-matlab:
    name: Run MATLAB Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024a
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: cd irest-matlab, toy_example
    commit-figures:
      name: Commit Matlab Figures
      runs-on: ubuntu-latest
      needs: run-matlab
      if: github.ref == 'refs/head/main'
      steps:
        - name: Commit Figures
          uses: EndBug/add-and-commit@v9
          with:
            add: irest-matlab/figures
            author_name: GitHub CI
